<?php

// Set your Cashfree credentials
$clientId = 'YOUR_CLIENT_ID';
$clientSecret = 'YOUR_CLIENT_SECRET';

// Set the API endpoint
$apiUrl = 'https://api.cashfree.com/api/v2/cftoken/order';

// Set order details
$orderData = array(
    'orderId' => 'ORDER_ID', // Unique order ID generated by your system
    'orderAmount' => 'ORDER_AMOUNT', // Order amount in INR
    'orderCurrency' => 'INR',
    'orderNote' => 'Order for products',
    'customerName' => 'Customer Name',
    'customerPhone' => 'CUSTOMER_PHONE',
    'customerEmail' => 'CUSTOMER_EMAIL',
    'returnUrl' => 'RETURN_URL', // URL where the customer will be redirected after payment completion
    'notifyUrl' => 'NOTIFY_URL', // URL where Cashfree will send transaction updates
);

// Encode order data to JSON
$orderJsonData = json_encode($orderData);

// Generate token
$ch = curl_init();
curl_setopt($ch, CURLOPT_URL, $apiUrl);
curl_setopt($ch, CURLOPT_POST, 1);
curl_setopt($ch, CURLOPT_POSTFIELDS, $orderJsonData);
curl_setopt($ch, CURLOPT_RETURNTRANSFER, true);
curl_setopt($ch, CURLOPT_HTTPHEADER, array(
    'Content-Type: application/json',
    'X-Client-Id: ' . $clientId,
    'X-Client-Secret: ' . $clientSecret,
));

$response = curl_exec($ch);
curl_close($ch);

// Decode JSON response
$responseData = json_decode($response, true);

// Check if token is generated successfully
if (isset($responseData['cftoken'])) {
    $cfToken = $responseData['cftoken'];
    // Redirect user to Cashfree payment page
    header('Location: https://test.cashfree.com/billpay/checkout/posttoken/' . $cfToken);
    exit();
} else {
    // Handle error
    echo "Error: " . $responseData['message'];
}
?>
